package mybatis.log.action.gui;

import com.intellij.openapi.project.Project;
import com.intellij.openapi.ui.VerticalFlowLayout;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import mybatis.log.action.MybatisLogProjectService;

import javax.swing.*;
import java.awt.*;

/**
 * @author bruce ge
 */
public class ListForm {
    private JPanel thePanel;
    private Project myProject;
    private JPanel panel1;

    public ListForm(Project project) {
        myProject = project;
        panel1 = new JPanel();
        createUIComponents();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel1.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        scrollPane1.setViewportView(thePanel);
    }

    public JPanel getThePanel() {
        thePanel.add(new MySqlForm(myProject, "Example", "select * from demo_user").getThePanel());
        MybatisLogProjectService.getInstance(myProject).setTheSqlPanel(thePanel);
        return panel1;
    }


    private void createUIComponents() {
        thePanel = new JPanel();
        thePanel.setLayout(new VerticalFlowLayout());
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {

    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
